# Generated by Django 5.0.8 on 2024-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_subtitle', models.CharField(max_length=100)),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(upload_to='static/')),
                ('slider_video_link', models.TextField()),
                ('slider_button1', models.CharField(max_length=100)),
                ('slider_button1_link', models.TextField()),
                ('slider_button2', models.CharField(max_length=100)),
                ('slider_button_link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
