# Generated by Django 5.0.8 on 2024-11-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_slider_delete_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_button_link',
            new_name='slider_button2_link',
        ),
    ]
