# Generated by Django 5.0.8 on 2024-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature_name',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_details',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(default='null', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
